target_type: 'aprilgrid' #gridtype
tagCols: 4               #number of apriltags
tagRows: 3               #number of apriltags
tagSize: 0.05            #size of apriltag, edge to edge [m]
tagSpacing: 0.25         #ratio of space between tags to tagSize
codeOffset: 0            #code offset for the first tag in the aprilboard
